name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build the Docker image
      run: docker build https://github.com/nickleus-j/EnglishDictionaryCaller.git#master
    - name: Tag the Docker image
      run: docker tag 903dd59b6430 nickleusj/englishdictionary:latest
    - name: Push the Docker image to the registry
      run: docker push nickleusj/englishdictionary:latest
